In [2]:
import torch

a = torch.Tensor([[2,3],[4,8],[7,9]])
print(a,a.size())

tensor([[2., 3.],
        [4., 8.],
        [7., 9.]]) torch.Size([3, 2])


In [4]:
b = torch.LongTensor([[2,3],[4,5],[6,7]])
b

tensor([[2, 3],
        [4, 5],
        [6, 7]])

In [12]:

numpy_b = b.numpy()
numpy_b

array([[2, 3],
       [4, 5],
       [6, 7]], dtype=int64)

In [14]:
import numpy as np
e = np.array([[1,2],[3,4]])
e

array([[1, 2],
       [3, 4]])

In [18]:
torch_e = torch.from_numpy(e)
torch_e.type()

'torch.IntTensor'

In [17]:
f_torch_e = torch_e.float()
f_torch_e.type()

'torch.FloatTensor'

In [19]:
if torch.cuda.is_available():
    a_cuda = a.cuda()
    print(a_cuda)

tensor([[2., 3.],
        [4., 8.],
        [7., 9.]], device='cuda:0')


In [40]:
from torch.autograd import Variable

x = Variable(torch.Tensor([1]), requires_grad = True)
w = Variable(torch.Tensor([2]), requires_grad = True)
b = Variable(torch.Tensor([3]), requires_grad = True)

y = w * x + b

y.backward()
           
print(x.grad)
print(w.grad)
print(b.grad)

tensor([2.])
tensor([1.])
tensor([1.])


In [46]:
x= torch.randn(3)
x=Variable(x,requires_grad = True)
print(x)
y = x*2

print(y)

y.backward(torch.FloatTensor([1,0.1,0.01]))
print(x.grad)

tensor([-0.7970, -1.7851,  0.3690], requires_grad=True)
tensor([-1.5941, -3.5702,  0.7381], grad_fn=<MulBackward0>)
tensor([2.0000, 0.2000, 0.0200])


In [47]:
torch.utils.data.Dataset

torch.utils.data.dataset.Dataset